package constants

import "golang.org/x/xerrors"

const (
	// SKK_CONTRACT_ADDRESS_TESTNET Governance coin ERC20
	SKK_CONTRACT_ADDRESS_TESTNET = "0x9835B7731017f52AdaDbB1d9f2E3aAA88C7D5Db6"
	SKK_CONTRACT_ADDRESS_MAINNET = ""

	// SKS_CONTRACT_ADDRESS_TESTNET Consumption coin ERC20
	SKS_CONTRACT_ADDRESS_TESTNET = "0xf469a2c958Cb0eEE939aBc09551175cD7BEfCb2F"
	SKS_CONTRACT_ADDRESS_MAINNET = ""

	// SOUL_CONTRACT_ADDRESS_TESTNET ERC721
	SOUL_CONTRACT_ADDRESS_TESTNET = "0x5c6Df032e709Bd387Fbfd77B7Dff752c268ef1B3"
	SOUL_CONTRACT_ADDRESS_MAINNET = ""
)

func GetContractAddress(number int) (string, error) {
	switch number {
	case 1:
		return SKK_CONTRACT_ADDRESS_TESTNET, nil
	case 2:
		return SKK_CONTRACT_ADDRESS_MAINNET, nil
	case 3:
		return SKS_CONTRACT_ADDRESS_TESTNET, nil
	case 4:
		return SKS_CONTRACT_ADDRESS_MAINNET, nil
	case 5:
		return SOUL_CONTRACT_ADDRESS_TESTNET, nil
	case 6:
		return SOUL_CONTRACT_ADDRESS_MAINNET, nil

	}
	return "", xerrors.New("ContractNumber is not exist")
}
